version: '3.8'

services:

  tailor:
    build: ../server/
    container_name: tailor
    image: tailor:microfrontend
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
    networks:
      - tailor_net

networks:
  tailor_net:
    driver: "bridge"
